//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.Settings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Module.Settings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальный адрес области загрузчика.
        /// </summary>
        public static string AddressOfBootLoaderBegin {
            get {
                return ResourceManager.GetString("AddressOfBootLoaderBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конечный адрес области загрузчика.
        /// </summary>
        public static string AddressOfBootLoaderEnd {
            get {
                return ResourceManager.GetString("AddressOfBootLoaderEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость передачи.
        /// </summary>
        public static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string ButtonTextAdd {
            get {
                return ResourceManager.GetString("ButtonTextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string ButtonTextCancel {
            get {
                return ResourceManager.GetString("ButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string ButtonTextRemove {
            get {
                return ResourceManager.GetString("ButtonTextRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string ButtonTextSelect {
            get {
                return ResourceManager.GetString("ButtonTextSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string ButtonTextUpdate {
            get {
                return ResourceManager.GetString("ButtonTextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить текущие настройки.
        /// </summary>
        public static string CanNotDeleteTheCurrentSettings {
            get {
                return ResourceManager.GetString("CanNotDeleteTheCurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные настройки уже выбраны.
        /// </summary>
        public static string CanNotSelectTheCurrentSettings {
            get {
                return ResourceManager.GetString("CanNotSelectTheCurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно изменить текущие настройки.
        /// </summary>
        public static string CanNotUpdateTheCurrentSettings {
            get {
                return ResourceManager.GetString("CanNotUpdateTheCurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер EEPROM-памяти (КБ).
        /// </summary>
        public static string EepromSize {
            get {
                return ResourceManager.GetString("EepromSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер FLASH-памяти (КБ).
        /// </summary>
        public static string FlashSize {
            get {
                return ResourceManager.GetString("FlashSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок на приём.
        /// </summary>
        public static string HeaderRx {
            get {
                return ResourceManager.GetString("HeaderRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовки не должны совпадать.
        /// </summary>
        public static string HeadersCanNotBeEqual {
            get {
                return ResourceManager.GetString("HeadersCanNotBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок на передачу.
        /// </summary>
        public static string HeaderTx {
            get {
                return ResourceManager.GetString("HeaderTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация SettingsModule....
        /// </summary>
        public static string InitializingSettingsModule {
            get {
                return ResourceManager.GetString("InitializingSettingsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлены новые настройки: {0}.
        /// </summary>
        public static string LogAddedNewSettings {
            get {
                return ResourceManager.GetString("LogAddedNewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалены настройки: {0}.
        /// </summary>
        public static string LogRemovedSettings {
            get {
                return ResourceManager.GetString("LogRemovedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбраны новые настройки: {0}.
        /// </summary>
        public static string LogSelectedSettings {
            get {
                return ResourceManager.GetString("LogSelectedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменены настройки: старое значение - {0}, новое значение - {1}.
        /// </summary>
        public static string LogUpdatedSettings {
            get {
                return ResourceManager.GetString("LogUpdatedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип памяти.
        /// </summary>
        public static string MemoryType {
            get {
                return ResourceManager.GetString("MemoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо ввести название.
        /// </summary>
        public static string NameСanNotBeEmpty {
            get {
                return ResourceManager.GetString("NameСanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бит паритета.
        /// </summary>
        public static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процессор.
        /// </summary>
        public static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки последовательного порта.
        /// </summary>
        public static string SerialPortSettings {
            get {
                return ResourceManager.GetString("SerialPortSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки с таким названием уже существуют.
        /// </summary>
        public static string SettingsWithTheSameNameAlreadyExists {
            get {
                return ResourceManager.GetString("SettingsWithTheSameNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоповые биты.
        /// </summary>
        public static string StopBits {
            get {
                return ResourceManager.GetString("StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новые настройки.
        /// </summary>
        public static string TitleAddNewSettings {
            get {
                return ResourceManager.GetString("TitleAddNewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выбранные настройки.
        /// </summary>
        public static string TitleRemoveSettings {
            get {
                return ResourceManager.GetString("TitleRemoveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать настройки.
        /// </summary>
        public static string TitleSelectSettings {
            get {
                return ResourceManager.GetString("TitleSelectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить настройки.
        /// </summary>
        public static string TitleUpdateSettings {
            get {
                return ResourceManager.GetString("TitleUpdateSettings", resourceCulture);
            }
        }
    }
}
