//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.Menu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Module.Menu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В системе обнаружены следующие COM-порты: {0}.
        /// </summary>
        public static string FoundTheFollowingPorts {
            get {
                return ResourceManager.GetString("FoundTheFollowingPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация MenuModule...
        /// </summary>
        public static string InitializingMenuModule {
            get {
                return ResourceManager.GetString("InitializingMenuModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string MenuHeaderFile {
            get {
                return ResourceManager.GetString("MenuHeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        public static string MenuHeaderLoading {
            get {
                return ResourceManager.GetString("MenuHeaderLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string MenuHeaderSettings {
            get {
                return ResourceManager.GetString("MenuHeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В системе не найдено ни одного COM-порта.
        /// </summary>
        public static string PortsNotFound {
            get {
                return ResourceManager.GetString("PortsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбран следующий порт: {0}.
        /// </summary>
        public static string SelectTheFollowingPort {
            get {
                return ResourceManager.GetString("SelectTheFollowingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть все.
        /// </summary>
        public static string SubMenuFileHeaderCloseAllFiles {
            get {
                return ResourceManager.GetString("SubMenuFileHeaderCloseAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string SubMenuFileHeaderCloseFile {
            get {
                return ResourceManager.GetString("SubMenuFileHeaderCloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сравнить файлы.
        /// </summary>
        public static string SubMenuFileHeaderCompareFiles {
            get {
                return ResourceManager.GetString("SubMenuFileHeaderCompareFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string SubMenuFileHeaderExit {
            get {
                return ResourceManager.GetString("SubMenuFileHeaderExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть файл.
        /// </summary>
        public static string SubMenuFileHeaderOpenFile {
            get {
                return ResourceManager.GetString("SubMenuFileHeaderOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить все.
        /// </summary>
        public static string SubMenuFileHeaderSaveAll {
            get {
                return ResourceManager.GetString("SubMenuFileHeaderSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как.
        /// </summary>
        public static string SubMenuFileHeaderSaveAs {
            get {
                return ResourceManager.GetString("SubMenuFileHeaderSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение.
        /// </summary>
        public static string SubMenuLoadingHeaderConnection {
            get {
                return ResourceManager.GetString("SubMenuLoadingHeaderConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка в EEPROM.
        /// </summary>
        public static string SubMenuLoadingHeaderDownloadingInEeprom {
            get {
                return ResourceManager.GetString("SubMenuLoadingHeaderDownloadingInEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка во FLASH.
        /// </summary>
        public static string SubMenuLoadingHeaderDownloadingInFlash {
            get {
                return ResourceManager.GetString("SubMenuLoadingHeaderDownloadingInFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стирание EEPROM.
        /// </summary>
        public static string SubMenuLoadingHeaderEraseEeprom {
            get {
                return ResourceManager.GetString("SubMenuLoadingHeaderEraseEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стирание FLASH.
        /// </summary>
        public static string SubMenuLoadingHeaderEraseFlash {
            get {
                return ResourceManager.GetString("SubMenuLoadingHeaderEraseFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение FUSE-бит.
        /// </summary>
        public static string SubMenuLoadingHeaderReadFuseBits {
            get {
                return ResourceManager.GetString("SubMenuLoadingHeaderReadFuseBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение LOCK-бит.
        /// </summary>
        public static string SubMenuLoadingHeaderReadLockBits {
            get {
                return ResourceManager.GetString("SubMenuLoadingHeaderReadLockBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс.
        /// </summary>
        public static string SubMenuLoadingHeaderReset {
            get {
                return ResourceManager.GetString("SubMenuLoadingHeaderReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение из EEPROM.
        /// </summary>
        public static string SubMenuLoadingHeaderUploadingFromEeprom {
            get {
                return ResourceManager.GetString("SubMenuLoadingHeaderUploadingFromEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение из FLASH.
        /// </summary>
        public static string SubMenuLoadingHeaderUploadingFromFlash {
            get {
                return ResourceManager.GetString("SubMenuLoadingHeaderUploadingFromFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string SubMenuSettingsHeaderAddNewSettings {
            get {
                return ResourceManager.GetString("SubMenuSettingsHeaderAddNewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать настройки.
        /// </summary>
        public static string SubMenuSettingsHeaderChangeSettings {
            get {
                return ResourceManager.GetString("SubMenuSettingsHeaderChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string SubMenuSettingsHeaderRemoveSettings {
            get {
                return ResourceManager.GetString("SubMenuSettingsHeaderRemoveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string SubMenuSettingsHeaderUpdateSettings {
            get {
                return ResourceManager.GetString("SubMenuSettingsHeaderUpdateSettings", resourceCulture);
            }
        }
    }
}
