//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.IO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Module.IO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение успешно завершено..
        /// </summary>
        public static string ConnectionCompleted {
            get {
                return ResourceManager.GetString("ConnectionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение завершено с ошибкой {0}.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение запущено.
        /// </summary>
        public static string ConnectionStarted {
            get {
                return ResourceManager.GetString("ConnectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение остановлено.
        /// </summary>
        public static string ConnectionStoped {
            get {
                return ResourceManager.GetString("ConnectionStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стирание {0} успешно завершено.
        /// </summary>
        public static string EraseCompleted {
            get {
                return ResourceManager.GetString("EraseCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стирание {0} завершено с ошибкой {1}.
        /// </summary>
        public static string EraseError {
            get {
                return ResourceManager.GetString("EraseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стирание {0} запущено.
        /// </summary>
        public static string EraseStarted {
            get {
                return ResourceManager.GetString("EraseStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стирание {0} остановлено.
        /// </summary>
        public static string EraseStoped {
            get {
                return ResourceManager.GetString("EraseStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация IOModule...
        /// </summary>
        public static string InitializingIOModule {
            get {
                return ResourceManager.GetString("InitializingIOModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ {0} успешно завершен.
        /// </summary>
        public static string IsEmptyCompleted {
            get {
                return ResourceManager.GetString("IsEmptyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ {0} завершен с ошибкой {1}.
        /// </summary>
        public static string IsEmptyError {
            get {
                return ResourceManager.GetString("IsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ {0} запущен.
        /// </summary>
        public static string IsEmptyStarted {
            get {
                return ResourceManager.GetString("IsEmptyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ {0} остановлен.
        /// </summary>
        public static string IsEmptyStoped {
            get {
                return ResourceManager.GetString("IsEmptyStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл загрузчика: версия {0} от {1}.
        /// </summary>
        public static string NotificationConnection {
            get {
                return ResourceManager.GetString("NotificationConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стирание успешно завершено.
        /// </summary>
        public static string NotificationErase {
            get {
                return ResourceManager.GetString("NotificationErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended: 0x{0:X2} Hight: 0x{1:X2} Low: 0x{2:X2}.
        /// </summary>
        public static string NotificationFuse {
            get {
                return ResourceManager.GetString("NotificationFuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock: 0x{0:X2}.
        /// </summary>
        public static string NotificationLock {
            get {
                return ResourceManager.GetString("NotificationLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение успешно завершено.
        /// </summary>
        public static string NotificationRead {
            get {
                return ResourceManager.GetString("NotificationRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс успешно завершен.
        /// </summary>
        public static string NotificationReset {
            get {
                return ResourceManager.GetString("NotificationReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись успешно завершена.
        /// </summary>
        public static string NotificationWrite {
            get {
                return ResourceManager.GetString("NotificationWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение {0} успешно завершено.
        /// </summary>
        public static string ReadCompleted {
            get {
                return ResourceManager.GetString("ReadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение {0} завершено с ошибкой {1}.
        /// </summary>
        public static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение FUSE-бит успешно завершено. Полученные значения: Extended=0x{0:X2}, Hight=0x{1:X2}, Low=0x{2:X2}.
        /// </summary>
        public static string ReadFuseCompleted {
            get {
                return ResourceManager.GetString("ReadFuseCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение FUSE-бит завершено с ошибкой {0}.
        /// </summary>
        public static string ReadFuseError {
            get {
                return ResourceManager.GetString("ReadFuseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение FUSE-бит запущено.
        /// </summary>
        public static string ReadFuseStarted {
            get {
                return ResourceManager.GetString("ReadFuseStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение FUSE-бит остановлено.
        /// </summary>
        public static string ReadFuseStoped {
            get {
                return ResourceManager.GetString("ReadFuseStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение LOCK-бит успешно завершено. Полученные значения: 0x{0:X2}.
        /// </summary>
        public static string ReadLockCompleted {
            get {
                return ResourceManager.GetString("ReadLockCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение LOCK-бит завершено с ошибкой {0}.
        /// </summary>
        public static string ReadLockError {
            get {
                return ResourceManager.GetString("ReadLockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение LOCK-бит запущено.
        /// </summary>
        public static string ReadLockStarted {
            get {
                return ResourceManager.GetString("ReadLockStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение LOCK-бит остановлено.
        /// </summary>
        public static string ReadLockStoped {
            get {
                return ResourceManager.GetString("ReadLockStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение {0} запущено.
        /// </summary>
        public static string ReadStarted {
            get {
                return ResourceManager.GetString("ReadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение {0} остановлено.
        /// </summary>
        public static string ReadStoped {
            get {
                return ResourceManager.GetString("ReadStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс успешно завершен.
        /// </summary>
        public static string ResetCompleted {
            get {
                return ResourceManager.GetString("ResetCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс завершен с ошибкой {0}.
        /// </summary>
        public static string ResetError {
            get {
                return ResourceManager.GetString("ResetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс запущен.
        /// </summary>
        public static string ResetStarted {
            get {
                return ResourceManager.GetString("ResetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс остановлен.
        /// </summary>
        public static string ResetStoped {
            get {
                return ResourceManager.GetString("ResetStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор файла.
        /// </summary>
        public static string SelectionFileTitle {
            get {
                return ResourceManager.GetString("SelectionFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ {0}....
        /// </summary>
        public static string TextAnalysis {
            get {
                return ResourceManager.GetString("TextAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение....
        /// </summary>
        public static string TextConnection {
            get {
                return ResourceManager.GetString("TextConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стирание {0}....
        /// </summary>
        public static string TextErase {
            get {
                return ResourceManager.GetString("TextErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение {0}....
        /// </summary>
        public static string TextRead {
            get {
                return ResourceManager.GetString("TextRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение FUSE-бит....
        /// </summary>
        public static string TextReadFuse {
            get {
                return ResourceManager.GetString("TextReadFuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение LOCK-бит....
        /// </summary>
        public static string TextReadLock {
            get {
                return ResourceManager.GetString("TextReadLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс....
        /// </summary>
        public static string TextReset {
            get {
                return ResourceManager.GetString("TextReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись {0}....
        /// </summary>
        public static string TextWrite {
            get {
                return ResourceManager.GetString("TextWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение.
        /// </summary>
        public static string TitleConnection {
            get {
                return ResourceManager.GetString("TitleConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стирание {0}.
        /// </summary>
        public static string TitleErase {
            get {
                return ResourceManager.GetString("TitleErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUSE-биты.
        /// </summary>
        public static string TitleFuse {
            get {
                return ResourceManager.GetString("TitleFuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCK-биты.
        /// </summary>
        public static string TitleLock {
            get {
                return ResourceManager.GetString("TitleLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение {0}.
        /// </summary>
        public static string TitleRead {
            get {
                return ResourceManager.GetString("TitleRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение FUSE-бит.
        /// </summary>
        public static string TitleReadFuse {
            get {
                return ResourceManager.GetString("TitleReadFuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение LOCK-бит.
        /// </summary>
        public static string TitleReadLock {
            get {
                return ResourceManager.GetString("TitleReadLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс.
        /// </summary>
        public static string TitleReset {
            get {
                return ResourceManager.GetString("TitleReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись {0}.
        /// </summary>
        public static string TitleWrite {
            get {
                return ResourceManager.GetString("TitleWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись {0} успешно завершена.
        /// </summary>
        public static string WriteCompleted {
            get {
                return ResourceManager.GetString("WriteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись {0} завершена с ошибкой {1}.
        /// </summary>
        public static string WriteError {
            get {
                return ResourceManager.GetString("WriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись {0} запущена.
        /// </summary>
        public static string WriteStarted {
            get {
                return ResourceManager.GetString("WriteStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись {0} остановлена.
        /// </summary>
        public static string WriteStoped {
            get {
                return ResourceManager.GetString("WriteStoped", resourceCulture);
            }
        }
    }
}
