//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.ToolBar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Module.ToolBar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare files.
        /// </summary>
        public static string CompareFiles {
            get {
                return ResourceManager.GetString("CompareFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading to EEPROM.
        /// </summary>
        public static string DownloadingInEeprom {
            get {
                return ResourceManager.GetString("DownloadingInEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading to FLASH.
        /// </summary>
        public static string DownloadingInFlash {
            get {
                return ResourceManager.GetString("DownloadingInFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erasing EEPROM.
        /// </summary>
        public static string EraseEeprom {
            get {
                return ResourceManager.GetString("EraseEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erasing FLASH.
        /// </summary>
        public static string EraseFlash {
            get {
                return ResourceManager.GetString("EraseFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system has the following COM-ports: {0}.
        /// </summary>
        public static string FoundTheFollowingPorts {
            get {
                return ResourceManager.GetString("FoundTheFollowingPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing ToolBarModule...
        /// </summary>
        public static string InitializingToolBarModule {
            get {
                return ResourceManager.GetString("InitializingToolBarModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports not found.
        /// </summary>
        public static string PortsNotFound {
            get {
                return ResourceManager.GetString("PortsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading FUSE-bits.
        /// </summary>
        public static string ReadFuseBits {
            get {
                return ResourceManager.GetString("ReadFuseBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading LOCK-bits.
        /// </summary>
        public static string ReadLockBits {
            get {
                return ResourceManager.GetString("ReadLockBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the following port: {0}.
        /// </summary>
        public static string SelectTheFollowingPort {
            get {
                return ResourceManager.GetString("SelectTheFollowingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading from EEPROM.
        /// </summary>
        public static string UploadingFromEeprom {
            get {
                return ResourceManager.GetString("UploadingFromEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading from FLASH.
        /// </summary>
        public static string UploadingFromFlash {
            get {
                return ResourceManager.GetString("UploadingFromFlash", resourceCulture);
            }
        }
    }
}
